In [19]:
!pip install git+https://github.com/LIAAD/yake 

  Cloning https://github.com/LIAAD/yake to c:\users\omar\appdata\local\temp\pip-req-build-kfzdloja
  Running setup.py bdist_wheel for yake: started
  Running setup.py bdist_wheel for yake: finished with status 'done'
  Stored in directory: C:\Users\Omar\AppData\Local\Temp\pip-ephem-wheel-cache-5kccj6e6\wheels\be\35\27\e4ebd54b78c1806ed8b0271ce247fcd91e2bedde35889fbc9b
  Running setup.py bdist_wheel for tabulate: started
  Running setup.py bdist_wheel for tabulate: finished with status 'done'
  Stored in directory: C:\Users\Omar\AppData\Local\pip\Cache\wheels\2b\67\89\414471314a2d15de625d184d8be6d38a03ae1e983dbda91e84
  Running setup.py bdist_wheel for segtok: started
  Running setup.py bdist_wheel for segtok: finished with status 'done'
  Stored in directory: C:\Users\Omar\AppData\Local\pip\Cache\wheels\15\ee\a8\6112173f1386d33eebedb3f73429cfa41a4c3084556bcee254
  Running setup.py bdist_wheel for jellyfish: started
  Running setup.py bdist_wheel for jellyfish: finished with status 'don

You are using pip version 18.0, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [21]:
!pip install Rouge

You are using pip version 18.0, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [22]:
!python -m pip install --upgrade pip

  Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
  Found existing installation: pip 18.0
    Uninstalling pip-18.0:
      Successfully uninstalled pip-18.0


In [10]:
s = ''.join(list(str(np.random.randint(-1000,1000,100))))
s.replace('\n' ,"")

'[-917 -787  811 -915 -931  973  865 -936  926 -952 -712 -755  634 -847  327   12 -379 -790 -506  388  611  561  327  949 -355   -5 -326  703 -153  528 -340  108 -902  353  690 -132  871  242  707  880  123  517  -40 -852  606 -538  887  -78 -627 -596  138  463  315  452 -648 -949 -945 -674  317  303  630  824  -32  187 -817 -247  694  355  736 -887 -357  316  678 -442  -30  824  263 -415 -481  918  783 -104   39    7   69 -864 -834 -993  373  104 -945   88 -243 -724 -625  265 -602 -965 -862  111]'

In [1]:
import numpy as np
import pandas as pd
import pdb
import string
import os
import re

from nltk.tokenize import word_tokenize
from nltk.stem.isri import ISRIStemmer

In [2]:
dubai_dir = r'data\EASC-UTF-8\Articles\Topic147\tourisms (8).txt'
dubai = open(dubai_dir, encoding="utf-8").read()
import document
import preprocess
import evaluate
pr = preprocess.Preprocess()
original_text = dubai
preprocessed_text = pr.get_clean_article(dubai)
sentences = pr.get_article_sentences(preprocessed_text)
original_sentences = pr.get_article_sentences(dubai)
paragraphs = pr.get_cleaned_article_paragraphes(preprocessed_text)
para_sent_list = pr.get_para_sentences(paragraphs)
tokenized_word_sentences = pr.get_tokenized_word_sentences(sentences)

In [6]:
print(original_text,"\n")
print(preprocessed_text,"\n")
print(sentences,"\n")
print(paragraphs,"\n")
print(para_sent_list,"\n")
print(len(paragraphs),"\n")
print(preprocessed_sentences,"\n")
print(tokenized_word_sentences,"\n")

إمارة دبي هي ثاني الإمارات المكونة لدولة الإمارات العربية المتحدة وعاصمتها مدينة دبي. تشكل هذه الإمارة مركزا هاما للمال والأعمال في العالم، ووجهة سياحية يقصدها الملايين من السياح سنوياً.دبي هي العاصمة الاقتصادية للإمارات العربية المتحدة، وقد تطورت تطوراً كبيراً خلال السنوات الماضية. الاقتصاد الحر والنشط في الإمارة وعدم وجود نظام ضريبي لعب دورا كبيرا في جذب المستثمرين من جميع أنحاء العالم. وتقع إمارة دبي بين إمارتي أبو ظبي والشارقة.
وأهل إمارة دبي ينحدرون من قبائل عربية متنوعة، على رأسها قبيلة آل بو فلاسه التي تنحدر منها أسرة آل مكتوم الحاكمة. وتقطنها قبائل بني كعب و آل بو فلاح وآل بو مهير والسودان والشوامس والبلوش والمناصير والرميثات والشحوح وغيرهم. وبها عوائل كثيرة من أصول أفريقية وفارسية. ودين أهالي دبي هو الإسلام على نهج أهل السنة والجماعة، والمذهب الرسمي في دبي هو المذهب المالكي.آل مكتوم هم حكام دبي. وهم من آل بو فلاسه من بني ياس. حاكمها الآن هو الشيخ محمد بن راشد آل مكتوم. وهو أيضا نائب لرئيس الدولة و رئيس لمجلس الوزراء في الحكومة الاتحادية. ونائبيه في الحكم هما: شقيقه الشيخ حمدا

In [7]:
doc = document.Doc(
    original_text = original_text ,  original_sentences = original_sentences ,
    preprocessed_text = preprocessed_text.replace('ppp',""),
    sentences = sentences,
    paragraphs = paragraphs ,para_sent_list = para_sent_list ,tokenized_word_sentences = tokenized_word_sentences)

In [4]:
doc.para_sent_list

[['مرة دبي هي ثني امر كون لدل امر عرب تحد عصم دين دبي ',
  ' شكل هذه مرة ركز هما مال عمل في علم وجه سيح قصد لاي من سيح سنويا',
  'دبي هي عصم اقتصادية امر عرب تحد وقد تطر تطر كبر خلل سنو اضة ',
  ' قصد لحر نشط في مرة عدم وجد نظم ضرب لعب دور كبر في جذب ثمر من جمع حاء علم ',
  ' تقع مرة دبي بين مرت ابو ظبي شارقة'],
 ['واهل مرة دبي حدر من قبءل عرب تنع علي راس قبل ال بو فلس التي حدر منها اسر ال كتم حكم ',
  ' تقط قبءل بني كعب و ال بو فلح وال بو هير سود شمس بلش مناصير رمث شحح وغر ',
  ' وبه عءل كثر من اصل فرق فرس ',
  ' ودن هلي دبي هو سلم علي نهج اهل سنة جمع ذهب رسم في دبي هو ذهب مالكي',
  'ال كتم هم حكم دبي ',
  ' وهم من ال بو فلس من بني ياس ',
  ' حكم الن هو شيخ حمد بن رشد ال كتم ',
  ' وهو ايض نءب رءس دول و رءس جلس زرء في حكم تحد ',
  ' نءب في حكم هما شقق شيخ حمد بن رشد ال كتم وزر الة صنع شيخ كتم بن حمد بن رشد ال كتم ',
  ' بين يتل نصب ولي عهد مرة شيخ حمد بن حمد بن رشد ال كتم رءس جلس نفذ مرة '],
 ['يراس جلس نفذ حكم دبي شيخ حمد بن حمد بن رشد ال كتم ',
  ' جمع هذا جلس في عضي جمع درء دءر في 

## Keyphrase Feaure 

In [4]:
sent1 = preprocessed_sentences[0]
sent1

'مرة دبي هي ثني امر كون لدل امر عرب تحد عصم دين دبي'

In [5]:
sent4 = preprocessed_sentences[4]
sent4

'تقع مرة دبي بين مرت ابو ظبي شارقة'

In [4]:
doc.key_phrases = doc.get_doc_key_phrase(preprocessed_text)
doc.key_phrases

[('حمد', 0.007180488319778574),
 ('رشد', 0.01047356012944052),
 ('دبي', 0.014069182047195363),
 ('كتم', 0.01476420150588332),
 ('حكم', 0.015706769515747496),
 ('مرة', 0.018413187070804565),
 ('شيخ', 0.02093572777391354),
 ('جلس', 0.026175977397234835),
 ('عرب', 0.030829509309901137),
 ('جمع', 0.03264921527469983),
 ('رءس', 0.035234302181788024),
 ('امر', 0.035234302181788024),
 ('تحد', 0.035234302181788024),
 ('نفذ', 0.04685698926833211),
 ('فلس', 0.04685698926833211)]

In [6]:
doc.key_phrase_frequency = doc.get_key_phrase_frequency(sent1)
doc.key_phrase_frequency

defaultdict(int,
            {'امر': 0.02702702702702703,
             'تحد': 0.04054054054054054,
             'جلس': 0.05405405405405406,
             'جمع': 0.04054054054054054,
             'حكم': 0.0945945945945946,
             'حمد': 0.05405405405405406,
             'دبي': 0.10810810810810811,
             'رءس': 0.02702702702702703,
             'رشد': 0.05405405405405406,
             'شيخ': 0.05405405405405406,
             'عرب': 0.04054054054054054,
             'فلس': 0.02702702702702703,
             'كتم': 0.08108108108108109,
             'مرة': 0.0945945945945946,
             'نفذ': 0.02702702702702703})

In [7]:
doc.get_key_phrase_proper_name()

{'امر': 1,
 'تحد': 1,
 'جلس': 1,
 'جمع': 1,
 'حكم': 1,
 'حمد': 1,
 'دبي': 1,
 'رءس': 1,
 'رشد': 1,
 'شيخ': 1,
 'عرب': 1,
 'فلس': 1,
 'كتم': 1,
 'مرة': 1,
 'نفذ': 1}

In [8]:
doc.get_key_phrase_length()

{'امر': 1.7320508075688772,
 'تحد': 1.7320508075688772,
 'جلس': 1.7320508075688772,
 'جمع': 1.7320508075688772,
 'حكم': 1.7320508075688772,
 'حمد': 1.7320508075688772,
 'دبي': 1.7320508075688772,
 'رءس': 1.7320508075688772,
 'رشد': 1.7320508075688772,
 'شيخ': 1.7320508075688772,
 'عرب': 1.7320508075688772,
 'فلس': 1.7320508075688772,
 'كتم': 1.7320508075688772,
 'مرة': 1.7320508075688772,
 'نفذ': 1.7320508075688772}

In [10]:
doc.get_topic_idf(sentences)

['ال',
 'امر',
 'بن',
 'بني',
 'بو',
 'بين',
 'تحد',
 'تطر',
 'جلس',
 'جمع',
 'حدر',
 'حكم',
 'حمد',
 'دبي',
 'دور',
 'ذهب',
 'رءس',
 'رشد',
 'سيح',
 'شيخ',
 'عرب',
 'عصم',
 'علم',
 'علي',
 'فلس',
 'في',
 'قبءل',
 'قصد',
 'كبر',
 'كتم',
 'مرة',
 'من',
 'نءب',
 'نفذ',
 'هما',
 'هو',
 'هي']

In [5]:
doc.get_key_phrase_score(sent1)

0

## Sentence Location Feature 

In [5]:
len(para_sent_list)

3

In [6]:
para_sent_list

[[['مرة دبي هي ثني امر كون لدل امر عرب تحد عصم دين دبي '],
  [' شكل هذه مرة ركز هما مال عمل في علم وجه سيح قصد لاي من سيح سنويا'],
  ['دبي هي عصم اقتصادية امر عرب تحد وقد تطر تطر كبر خلل سنو اضة '],
  [' قصد لحر نشط في مرة عدم وجد نظم ضرب لعب دور كبر في جذب ثمر من جمع حاء علم '],
  [' تقع مرة دبي بين مرت ابو ظبي شارقة']],
 [['واهل مرة دبي حدر من قبءل عرب تنع علي راس قبل ال بو فلس التي حدر منها اسر ال كتم حكم '],
  [' تقط قبءل بني كعب و ال بو فلح وال بو هير سود شمس بلش مناصير رمث شحح وغر '],
  [' وبه عءل كثر من اصل فرق فرس '],
  [' ودن هلي دبي هو سلم علي نهج اهل سنة جمع ذهب رسم في دبي هو ذهب مالكي'],
  ['ال كتم هم حكم دبي '],
  [' وهم من ال بو فلس من بني ياس '],
  [' حكم الن هو شيخ حمد بن رشد ال كتم '],
  [' وهو ايض نءب رءس دول و رءس جلس زرء في حكم تحد '],
  [' نءب في حكم هما شقق شيخ حمد بن رشد ال كتم وزر الة صنع شيخ كتم بن حمد بن رشد ال كتم '],
  [' بين يتل نصب ولي عهد مرة شيخ حمد بن حمد بن رشد ال كتم رءس جلس نفذ مرة ']],
 [['يراس جلس نفذ حكم دبي شيخ حمد بن حمد بن رشد ال كتم '],
  [' ج

In [11]:
for paragrpah_index,list_para in enumerate(para_sent_list) : print (list_para)

[['مرة دبي هي ثني امر كون لدل امر عرب تحد عصم دين دبي '], [' شكل هذه مرة ركز هما مال عمل في علم وجه سيح قصد لاي من سيح سنويا'], ['دبي هي عصم اقتصادية امر عرب تحد وقد تطر تطر كبر خلل سنو اضة '], [' قصد لحر نشط في مرة عدم وجد نظم ضرب لعب دور كبر في جذب ثمر من جمع حاء علم '], [' تقع مرة دبي بين مرت ابو ظبي شارقة']]
[['واهل مرة دبي حدر من قبءل عرب تنع علي راس قبل ال بو فلس التي حدر منها اسر ال كتم حكم '], [' تقط قبءل بني كعب و ال بو فلح وال بو هير سود شمس بلش مناصير رمث شحح وغر '], [' وبه عءل كثر من اصل فرق فرس '], [' ودن هلي دبي هو سلم علي نهج اهل سنة جمع ذهب رسم في دبي هو ذهب مالكي'], ['ال كتم هم حكم دبي '], [' وهم من ال بو فلس من بني ياس '], [' حكم الن هو شيخ حمد بن رشد ال كتم '], [' وهو ايض نءب رءس دول و رءس جلس زرء في حكم تحد '], [' نءب في حكم هما شقق شيخ حمد بن رشد ال كتم وزر الة صنع شيخ كتم بن حمد بن رشد ال كتم '], [' بين يتل نصب ولي عهد مرة شيخ حمد بن حمد بن رشد ال كتم رءس جلس نفذ مرة ']]
[['يراس جلس نفذ حكم دبي شيخ حمد بن حمد بن رشد ال كتم '], [' جمع هذا جلس في عضي جمع درء دءر في 

In [12]:
list_para[0]

['يراس جلس نفذ حكم دبي شيخ حمد بن حمد بن رشد ال كتم ']

In [7]:
doc.sentence_location_score(sent1)

3

In [8]:
doc.sentence_location_score(sent4)

0.5

In [43]:
l = [[1,0,0], [0,4,0], [0,0,1], [3,0,0]]
l = [[0 if x == 1 else x for x in sub_l] for sub_l in l]
l

[[0, 0, 0], [0, 4, 0], [0, 0, 0], [3, 0, 0]]

In [5]:
doc.tf_idf,doc.centroid_vector = doc.get_tfidf_centroid_vector(sentences)

In [6]:
tf.shape #17 sentence , 18 word

NameError: name 'tf' is not defined

In [11]:
vec.shape

(128,)

In [8]:
for i in range(len(doc.tf_idf)) :
    print(doc.cosine_similarity_V1(doc.tf_idf[i],doc.centroid_vector))

0.29439505573142427
0.21786101034832578
0.24914254038260608
0.2427804472278084
0.12804386248161473
0.37797468225530256
0.13212632061410423
0.04728940710967362
0.2554594692281977
0.3446235862545231
0.2751218971196341
0.5357681729708738
0.24825499757508376
0.5765072137550332
0.526205790734049
0.6067953722246339
0.27329371889482756


In [2]:
from scipy import spatial

a = [3, 45, 7, 2]
b = [2, 54, 13, 15]
result = 1 - spatial.distance.cosine(a, b)
result

0.97228425171235

In [3]:
from numpy import dot
from numpy.linalg import norm

cos_sim = dot(a, b)/(norm(a)*norm(b))
cos_sim

0.9722842517123499

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
 'This is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit(corpus)
print(vectorizer.get_feature_names())
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
#print(X.shape)


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [22]:
X.transform(['This document is the second documen']).toarray()

array([[0.        , 0.42796959, 0.        , 0.34989318, 0.        ,
        0.67049706, 0.34989318, 0.        , 0.34989318]])

In [8]:
sentences


['مرة دبي هي ثني امر كون لدل امر عرب تحد عصم دين دبي ',
 ' شكل هذه مرة ركز هما مال عمل في علم وجه سيح قصد لاي من سيح سنويا',
 'دبي هي عصم اقتصادية امر عرب تحد وقد تطر تطر كبر خلل سنو اضة ',
 ' قصد لحر نشط في مرة عدم وجد نظم ضرب لعب دور كبر في جذب ثمر من جمع حاء علم ',
 ' تقع مرة دبي بين مرت ابو ظبي شارقة',
 'واهل مرة دبي حدر من قبءل عرب تنع علي راس قبل ال بو فلس التي حدر منها اسر ال كتم حكم ',
 ' تقط قبءل بني كعب و ال بو فلح وال بو هير سود شمس بلش مناصير رمث شحح وغر ',
 ' وبه عءل كثر من اصل فرق فرس ',
 ' ودن هلي دبي هو سلم علي نهج اهل سنة جمع ذهب رسم في دبي هو ذهب مالكي',
 'ال كتم هم حكم دبي ',
 ' وهم من ال بو فلس من بني ياس ',
 ' حكم الن هو شيخ حمد بن رشد ال كتم ',
 ' وهو ايض نءب رءس دول و رءس جلس زرء في حكم تحد ',
 ' نءب في حكم هما شقق شيخ حمد بن رشد ال كتم وزر الة صنع شيخ كتم بن حمد بن رشد ال كتم ',
 ' بين يتل نصب ولي عهد مرة شيخ حمد بن حمد بن رشد ال كتم رءس جلس نفذ مرة ',
 'يراس جلس نفذ حكم دبي شيخ حمد بن حمد بن رشد ال كتم ',
 ' جمع هذا جلس في عضي جمع درء دءر في حكم دبي حيث عقدو اج

In [1]:
(0.4  * 17)/100

0.068

In [15]:
vec_sentence = doc.tf_idf.transform([sent1.strip()]).toarray()[0]
vec_sentence = np.squeeze(vec_sentence)
vec_sentence.shape

(128,)

In [16]:
doc.cosine_similarity_V1(vec_sentence ,doc.centroid_vector)

0.27121257153300155

In [11]:
len(sentences)

17

In [12]:
org_sentences = pr.get_article_sentences(dubai)
len(org_sentences)

17

# Centrality Feature

In [5]:
from  sklearn.metrics.pairwise import cosine_similarity

In [18]:
vecs = doc.tf_idf.transform(sentences)
vecs.shape

(17, 128)

In [25]:
cosine_similarity(vecs,vecs).shape
cos = cosine_similarity(vecs,vecs)

In [17]:
vec_sentence = doc.tf_idf.transform([sent1.strip()]).toarray()[0]
vec_sentence.shape

(128,)

In [21]:
cosine_similarity(vec_sentence.reshape(1,-1),vecs).shape

(1, 17)

In [22]:
cos_1 = cosine_similarity(vec_sentence.reshape(1,-1),vecs)
cos_1

array([[1.        , 0.01975356, 0.36042234, 0.01973309, 0.08396446,
        0.09140867, 0.        , 0.        , 0.06385184, 0.09435213,
        0.        , 0.        , 0.05392681, 0.        , 0.04406395,
        0.04938631, 0.05564071]])

In [26]:
cos[0]

array([1.        , 0.01975356, 0.36042234, 0.01973309, 0.08396446,
       0.09140867, 0.        , 0.        , 0.06385184, 0.09435213,
       0.        , 0.        , 0.05392681, 0.        , 0.04406395,
       0.04938631, 0.05564071])

In [30]:
cos[1]

array([0.01975356, 1.        , 0.        , 0.16710045, 0.02540058,
       0.03731566, 0.        , 0.03466491, 0.0178435 , 0.        ,
       0.07505607, 0.        , 0.02479303, 0.05864348, 0.03635106,
       0.        , 0.05622045])

In [32]:
np.where(cos[1] > 0.1)

(array([1, 3], dtype=int64),)

In [34]:
len(np.where(cos[1] > 0.1)[0])

2

In [28]:
np.equal(cos[0],cos_1[0])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
features = [doc.get_key_phrase_score ,doc.sentence_location_score,doc.get_centroid_score,
                    doc.get_centrality_score ,doc.sentence_length_score ,doc.cue_phrases_score ,
                    doc.strong_words_score]

In [20]:
def score(sentences) :    
    lst = []
    ordered_list = []
    max_legnth_summary = 5
    summary  = []
    sentence_scores = []
    for index,sentence in enumerate(sentences) :
        total_score = 0
        for feature in features :
            score = feature(sentence)
            total_score += score
        sentence_scores.append((index,total_score))


    ordered_list = sorted(sentence_scores,key =  lambda x : x[1] ,reverse = True)
    summary = ordered_list[:max_legnth_summary] 
    
    #pdb.set_trace()
    last_summary = sorted(summary,key =  lambda x : x[0])
    sum_list = [original_sentences[x] for (x,y) in last_summary]
    text_list = ".".join(sum_list)
    return text_list

    
  
  

In [21]:
score(sentences)

'\ufeffإمارة دبي هي ثاني الإمارات المكونة لدولة الإمارات العربية المتحدة وعاصمتها مدينة دبي.وأهل إمارة دبي ينحدرون من قبائل عربية متنوعة، على رأسها قبيلة آل بو فلاسه التي تنحدر منها أسرة آل مكتوم الحاكمة.ونائبيه في الحكم هما: شقيقه الشيخ حمدان بن راشد آل مكتوم وزير المالية والصناعة والشيخ مكتوم بن محمد بن راشد آل مكتوم.بينما يتولى منصب ولاية العهد بالإمارة الشيخ حمدان بن محمد بن راشد آل مكتوم رئيس المجلس التنفيذي للإمارة.يرأس المجلس التنفيذي لحكومة دبي الشيخ حمدان بن محمد بن راشد آل مكتوم'

In [ ]:
%run run_files.py --i  t1.txt 


> c:\users\omar\anacondaprojects\arabic_extractive_text_summarizer\run_files.py(44)run()
-> with open(output_path,'w' ,encoding = "utf-8") as f: f.write(summary)
(Pdb) summary
'\ufeffقضية لوكربي هي قضية جنائية ترتبت على سقوط طائرة ركاب أميركية أثناء تحليقها فوق قرية لوكربي Lockerbie باسكتلندا سنة 1988.بعد تحقيقات ليست معلنة ، وبعد تكهنات من وسائل الاعلام بتدوير المسؤلية بين دول مختلفة، يجمع بينها رابط العداء لاميركا ، وحركات تحرير تضعها اميركا في خانة المنظمات الارهابية ، ودون سابق انذار وبالتزامن صدر في الولايات المتحدة الأميركية و بريطانيا في 13 نوفمبر 1991 أمرا بالقبض على مواطنين ليبيين يشتبه في مسؤليتها عن تفجير الطائرة كونهما يعملان بمكتب شركة الخطوط الجوية الليبية بمطار لوقا بمالطا وبمعرفتهما تم شحن حقيبة تحتوي على متفجرات.على الفور رفضت ليبيا الطلب وبدأ القضاء الليبي التحقيق في الاتهام و اوقف المواطنان الليبيان وطلب من الدولتين تقديم مالديهما من ادلة ضدّهما.بدأت الدولتان بأستغلال تاثيرهما في التحرك داخل مجلس الأمن حتّى تمكنتا من اصدار قرار من المجلس المذكور في 31 مارس 1992 يحمل 

In [5]:
!ipython run_files.py t1.txt 